### ISSUE TITLE
Fix: too many request issue

### ISSUE THREAD

**Issue by PabloSanchi** [IBM/watsonx-go#16]
Watsonx.ai SaaS only allows 8 requests per second, but when doing some load tests simulating real user scenarios we can easily get to this issue, I suggest remediating this by applying some retry with backoff with jittering to handle large amounts of simultaneous requests.

**Comment by PabloSanchi** [comment]
@h0rv if possible we could discuss this on Slack to see other possible remediations :)

**Comment by PabloSanchi** [comment]
I have seen this module from Avast, https://pkg.go.dev/github.com/avast/retry-go, it seems pretty good

**Comment by h0rv** [comment]
Hi @PabloSanchi, this package is striving to be a 0 dependencies watsonx client (see [go.mod](https://github.com/IBM/watsonx-go/blob/main/go.mod)).

We are trying to keep it lightweight and not bring any 3rd party dependencies. Due to this, we should create our own solution, even if its not as sophisticated as a pkg like `retry-go`

**Comment by PabloSanchi** [comment]
Perfect, you are right. Then I will try to make a module for it. Thanks :)

**Comment by h0rv** [comment]
Merged the PR adding retries with backoff and jitter. Thanks for the contribution!
